### ISSUE TITLE
Module '"../../../../node_modules/gridjs-angular/gridjs-angular"' has no exported member 'GridJsConfig'.

### ISSUE THREAD

**Issue by TammyCT** [grid-js/gridjs-angular#89]
![image](https://user-images.githubusercontent.com/31911204/114985041-eeac9b00-9ec4-11eb-9547-4be11c5ff43f.png)

![image](https://user-images.githubusercontent.com/31911204/114984881-bdcc6600-9ec4-11eb-832b-249b7bed319f.png)

===========================
If I still use it, then the error will also appear.
![image](https://user-images.githubusercontent.com/31911204/114984752-a2615b00-9ec4-11eb-872b-072588b6255c.png)

**Comment by aaronbach** [comment]
I have the exact same Error. Have you figured out a workaround?

**Comment by rohithkumar001** [comment]
> I have the exact same Error. Have you figured out a workaround?

Same here, unable to figure it out.

**Comment by afshinm** [comment]
@salamaashoush would you be able to help with this?

**Comment by salamaashoush** [comment]
@TammyCT `gridjs-angular` does not export grid config type anymore, instead, it uses the one from  `gridjs` package

```
import { UserConfig } from 'gridjs';
```
I will update the docs
